id: IE7080666
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:09:07+00:00'
last_modified: '2022-06-08T09:10:06.273236+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W20823
  title: ཁ་གྱའི་སྒར་རྙིང་དགོན་དང་ཁ་གྱ་སྤྱིའི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '4292':
      image_group_id: I1GS105533
      title: ''
      total_pages: 96
      order: 1
      base_file: 4292.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
